package com.bwei.iloginorregui.core.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bwei.iloginorregui.bean.ubean.UserInfo;
import com.bwei.iloginorregui.bean.sbean.ShoppingBean;

import com.bwei.iloginorregui.core.db.UserInfoDao;
import com.bwei.iloginorregui.core.db.ShoppingBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig shoppingBeanDaoConfig;

    private final UserInfoDao userInfoDao;
    private final ShoppingBeanDao shoppingBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        shoppingBeanDaoConfig = daoConfigMap.get(ShoppingBeanDao.class).clone();
        shoppingBeanDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        shoppingBeanDao = new ShoppingBeanDao(shoppingBeanDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(ShoppingBean.class, shoppingBeanDao);
    }
    
    public void clear() {
        userInfoDaoConfig.clearIdentityScope();
        shoppingBeanDaoConfig.clearIdentityScope();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public ShoppingBeanDao getShoppingBeanDao() {
        return shoppingBeanDao;
    }

}
